### PR TITLE
Avoid deploy on PR + branch limited deploys

### PR DESCRIPTION
**Pull request by mathiasrw**
With this change deploy is avoided on pull requests

It also implements limiting deploy to one branch (here master)  as requested in #1

### CODE REVIEW

**Comment by mathiasrw** [comment]
Hmm... thinking about it - we do need another approach - people can just remove the check in the code they are pull requesting...

**Comment by mathiasrw** [comment]
I have contacted Travis to hear what it takes to get Surge on the [list of supported providers](https://docs.travis-ci.com/user/deployment/#Supported-Providers) so people can deploy via Travis to Surge the right way.

**Comment by mathiasrw** [comment]
Ok - its working! 

http://travis-loves-surge.surge.sh was released via Travis as a deploy provider ([see log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/119932445/log.txt) close to the end). Now we just need travis to merge the changes so everyone can use it. 

What you ned to do is to set SURGE_LOGIN and SURGE_TOKEN and in your `.travis.yml` have 

``` yaml
deploy:
  provider: surge
```

to get it rolling. 

If you dont have a CNAME file you need to add `domain`

``` yaml
deploy:
  provider: surge
  domain: myDomain.foo.bar
```

If project folder is not root of the repo the path can be set

``` yaml
deploy:
  provider: surge
  project: ./dist/
```

**Comment by kennethormandy** [comment]
This is great, thank you! Did Travis end up doing something on their end to make that possible?

/cc @sintaxi

**Comment by mathiasrw** [comment]
Nope. I cloned a repo and added surge as a provider. Working on some finetuning of the ruby code (not used to it) - but the good ting is that they already commented on the PR

**Comment by mathiasrw** [comment]
A lot of back and forth... but looks like we are now getting close...

**Pull request closed without merging**
